networks:
  asvsp-chess-project:
    name: asvsp-chess-project
    external: true

services:
  spark-master:
    #image: bde2020/spark-master:3.0.1-hadoop3.2
    build: .
    container_name: spark-master
    ports:
      - 8000:8080
      - 7077:7077
      - 22:22
    environment:
      - PYSPARK_PYTHON=python3
    volumes:
      - ./spark/jobs:/home/jobs/
    env_file:
      - .env
    networks:
      - asvsp-chess-project

  spark-worker-1:
    #image: bde2020/spark-worker:3.0.1-hadoop3.2
    build:
      context: .
      dockerfile: WorkerDockerfile
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8001:8081
    env_file:
      - .env
    networks:
      - asvsp-chess-project

  spark-worker-2:
    #image: bde2020/spark-worker:3.0.1-hadoop3.2
    build:
      context: .
      dockerfile: WorkerDockerfile
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8002:8081
    env_file:
      - .env
    networks:
      - asvsp-chess-project
